#first index =======================
filebeat.inputs:

- type: log
  id: my-filestream-id
  enabled: true
  paths:
    - /home/roeihafifot/logs.txt
  include_lines: ['^error']


# ======================= Elasticsearch template setting =======================

setup.template.name: "fastapi_error-template"
setup.template.pattern: "fastapi_error-*"


setup.template.settings:
  index.number_of_shards: 1


# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["20.86.28.57:9200"]
  index: "fastapi_error-%{+yyyy.MM.dd}"
  # Protocol - either `http` (default) or `https`.
  protocol: "https"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "elastic"
  password: "roei1234"
  ssl.certificate_authorities: ["/home/roeihafifot/http_ca.crt"]


# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  
# ============================== Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
