#first index =======================
filebeat.inputs:

- type: log
  id: my-filestream-id
  enabled: true
  paths:
    - /home/roeihafifot/logs.txt
  include_lines: ['^success']
  
# ======================= Elasticsearch template setting =======================

setup.template.name: "fastapi_success-template"
setup.template.pattern: "fastapi_success-*"


setup.template.settings:
  index.number_of_shards: 1


# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["20.86.28.57:9200"]
  index: "fastapi_success-%{+yyyy.MM.dd}"
  # Protocol - either `http` (default) or `https`.
  protocol: "https"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "elastic"
  password: "roei1234"
  ssl.certificate_authorities: ["/home/roeihafifot/http_ca.crt"]


# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - drop_fields:
      fields: ["log.file.path", "host.os.name.text", "host.mac", "host.ip", "cloud.instance.id", "agent.type", "host.os.version", "host.os.kernel", "host.os.name", "agent.name", "host.name", "host.id", "host.os.type", "cloud.region", "host.os.codename", "input.type", "log.offset", "agent.hostname", "host.architecture", "cloud.provider", "cloud.machine.type", "agent.id", "cloud.service.name", "ecs.version", "host.containerized", "host.os.platform", "agent.ephemeral_id", "agent.version", "host.os.family", "cloud.instance.name"]
      ignore_missing: true
# ============================== Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
