name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
         python3 -m pip install pycryptodome
         pip install fastapi
         pip install python-multipart
         cd Tests
         cp test_ftp.py test_fastapi.py /home/roeihafifot/final_tests/actions-runner/_work/final
         cd /home/roeihafifot/final_tests/actions-runner/_work/final
         echo --------------- this is the unittest for the FTP_server ---------------
         sudo python3 -m unittest test_ftp.py
         echo --------------- this is the unittest for the FASTAPI_server ---------------
         python3 test_fastapi.py
         cd final/ftp_server
         sudo rm -rf __pycache__
         cd ..
         cd utils 
         sudo rm -rf __pycache__
         
       
