name: CD-fastAPI
on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

  workflow_dispatch:

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: SSH into production server
        uses: appleboy/ssh-action@master
        with:
          host: 108.143.233.99
          username: roeihafifot
          key: ${{secrets.CD_SK}}
          port: 22
          script: |
            sudo apt install python3-pip
            # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install uvicorn
            pip install pycryptodome
            pip install fastapi
            pip install python-multipart
            git clone https://github.com/Rsagiv/final.git
            cd final
            git pull origin main
            cd fastapi_server
            cp -r fastapifunc.py http_ca.crt logs.txt uploaded_photos /home/roeihafifot
            python3 fastapifunc.py 
            
            
            
            
